// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: publication.proto

package publicationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicationService_CreatePublication_FullMethodName = "/publication.PublicationService/CreatePublication"
	PublicationService_GetPublication_FullMethodName    = "/publication.PublicationService/GetPublication"
	PublicationService_ListPublications_FullMethodName  = "/publication.PublicationService/ListPublications"
)

// PublicationServiceClient is the client API for PublicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC con endpoints REST vía grpc-gateway
type PublicationServiceClient interface {
	CreatePublication(ctx context.Context, in *CreatePublicationRequest, opts ...grpc.CallOption) (*CreatePublicationResponse, error)
	GetPublication(ctx context.Context, in *GetPublicationRequest, opts ...grpc.CallOption) (*GetPublicationResponse, error)
	ListPublications(ctx context.Context, in *ListPublicationsRequest, opts ...grpc.CallOption) (*ListPublicationsResponse, error)
}

type publicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicationServiceClient(cc grpc.ClientConnInterface) PublicationServiceClient {
	return &publicationServiceClient{cc}
}

func (c *publicationServiceClient) CreatePublication(ctx context.Context, in *CreatePublicationRequest, opts ...grpc.CallOption) (*CreatePublicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePublicationResponse)
	err := c.cc.Invoke(ctx, PublicationService_CreatePublication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicationServiceClient) GetPublication(ctx context.Context, in *GetPublicationRequest, opts ...grpc.CallOption) (*GetPublicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicationResponse)
	err := c.cc.Invoke(ctx, PublicationService_GetPublication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicationServiceClient) ListPublications(ctx context.Context, in *ListPublicationsRequest, opts ...grpc.CallOption) (*ListPublicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicationsResponse)
	err := c.cc.Invoke(ctx, PublicationService_ListPublications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicationServiceServer is the server API for PublicationService service.
// All implementations must embed UnimplementedPublicationServiceServer
// for forward compatibility.
//
// Servicio gRPC con endpoints REST vía grpc-gateway
type PublicationServiceServer interface {
	CreatePublication(context.Context, *CreatePublicationRequest) (*CreatePublicationResponse, error)
	GetPublication(context.Context, *GetPublicationRequest) (*GetPublicationResponse, error)
	ListPublications(context.Context, *ListPublicationsRequest) (*ListPublicationsResponse, error)
	mustEmbedUnimplementedPublicationServiceServer()
}

// UnimplementedPublicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicationServiceServer struct{}

func (UnimplementedPublicationServiceServer) CreatePublication(context.Context, *CreatePublicationRequest) (*CreatePublicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePublication not implemented")
}
func (UnimplementedPublicationServiceServer) GetPublication(context.Context, *GetPublicationRequest) (*GetPublicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublication not implemented")
}
func (UnimplementedPublicationServiceServer) ListPublications(context.Context, *ListPublicationsRequest) (*ListPublicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublications not implemented")
}
func (UnimplementedPublicationServiceServer) mustEmbedUnimplementedPublicationServiceServer() {}
func (UnimplementedPublicationServiceServer) testEmbeddedByValue()                            {}

// UnsafePublicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicationServiceServer will
// result in compilation errors.
type UnsafePublicationServiceServer interface {
	mustEmbedUnimplementedPublicationServiceServer()
}

func RegisterPublicationServiceServer(s grpc.ServiceRegistrar, srv PublicationServiceServer) {
	// If the following call panics, it indicates UnimplementedPublicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicationService_ServiceDesc, srv)
}

func _PublicationService_CreatePublication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicationServiceServer).CreatePublication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicationService_CreatePublication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicationServiceServer).CreatePublication(ctx, req.(*CreatePublicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicationService_GetPublication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicationServiceServer).GetPublication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicationService_GetPublication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicationServiceServer).GetPublication(ctx, req.(*GetPublicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicationService_ListPublications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicationServiceServer).ListPublications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicationService_ListPublications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicationServiceServer).ListPublications(ctx, req.(*ListPublicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicationService_ServiceDesc is the grpc.ServiceDesc for PublicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "publication.PublicationService",
	HandlerType: (*PublicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePublication",
			Handler:    _PublicationService_CreatePublication_Handler,
		},
		{
			MethodName: "GetPublication",
			Handler:    _PublicationService_GetPublication_Handler,
		},
		{
			MethodName: "ListPublications",
			Handler:    _PublicationService_ListPublications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publication.proto",
}
