// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: publication.proto

package publicationpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TipoServicio int32

const (
	TipoServicio_TIPO_SERVICIO_UNSPECIFIED TipoServicio = 0
	TipoServicio_OFERTA                    TipoServicio = 1
	TipoServicio_DEMANDA                   TipoServicio = 2
)

// Enum value maps for TipoServicio.
var (
	TipoServicio_name = map[int32]string{
		0: "TIPO_SERVICIO_UNSPECIFIED",
		1: "OFERTA",
		2: "DEMANDA",
	}
	TipoServicio_value = map[string]int32{
		"TIPO_SERVICIO_UNSPECIFIED": 0,
		"OFERTA":                    1,
		"DEMANDA":                   2,
	}
)

func (x TipoServicio) Enum() *TipoServicio {
	p := new(TipoServicio)
	*p = x
	return p
}

func (x TipoServicio) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TipoServicio) Descriptor() protoreflect.EnumDescriptor {
	return file_publication_proto_enumTypes[0].Descriptor()
}

func (TipoServicio) Type() protoreflect.EnumType {
	return &file_publication_proto_enumTypes[0]
}

func (x TipoServicio) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TipoServicio.Descriptor instead.
func (TipoServicio) EnumDescriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{0}
}

type EstadoPublicacion int32

const (
	EstadoPublicacion_ESTADO_PUBLICACION_UNSPECIFIED EstadoPublicacion = 0
	EstadoPublicacion_ACTIVO                         EstadoPublicacion = 1
	EstadoPublicacion_PAUSADO                        EstadoPublicacion = 2
	EstadoPublicacion_COMPLETADO                     EstadoPublicacion = 3
	EstadoPublicacion_ELIMINADO                      EstadoPublicacion = 4
)

// Enum value maps for EstadoPublicacion.
var (
	EstadoPublicacion_name = map[int32]string{
		0: "ESTADO_PUBLICACION_UNSPECIFIED",
		1: "ACTIVO",
		2: "PAUSADO",
		3: "COMPLETADO",
		4: "ELIMINADO",
	}
	EstadoPublicacion_value = map[string]int32{
		"ESTADO_PUBLICACION_UNSPECIFIED": 0,
		"ACTIVO":                         1,
		"PAUSADO":                        2,
		"COMPLETADO":                     3,
		"ELIMINADO":                      4,
	}
)

func (x EstadoPublicacion) Enum() *EstadoPublicacion {
	p := new(EstadoPublicacion)
	*p = x
	return p
}

func (x EstadoPublicacion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstadoPublicacion) Descriptor() protoreflect.EnumDescriptor {
	return file_publication_proto_enumTypes[1].Descriptor()
}

func (EstadoPublicacion) Type() protoreflect.EnumType {
	return &file_publication_proto_enumTypes[1]
}

func (x EstadoPublicacion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstadoPublicacion.Descriptor instead.
func (EstadoPublicacion) EnumDescriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{1}
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdCategoria   uint32                 `protobuf:"varint,1,opt,name=id_categoria,json=idCategoria,proto3" json:"id_categoria,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	IconoUrl      *string                `protobuf:"bytes,4,opt,name=icono_url,json=iconoUrl,proto3,oneof" json:"icono_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_publication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetIdCategoria() uint32 {
	if x != nil {
		return x.IdCategoria
	}
	return 0
}

func (x *Category) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetIconoUrl() string {
	if x != nil && x.IconoUrl != nil {
		return *x.IconoUrl
	}
	return ""
}

// Entidad Publicación completa
type Publication struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdPublicacion     uint32                 `protobuf:"varint,1,opt,name=id_publicacion,json=idPublicacion,proto3" json:"id_publicacion,omitempty"`
	IdUsuarioVendedor uint32                 `protobuf:"varint,2,opt,name=id_usuario_vendedor,json=idUsuarioVendedor,proto3" json:"id_usuario_vendedor,omitempty"`
	CategoriaId       uint32                 `protobuf:"varint,3,opt,name=categoria_id,json=categoriaId,proto3" json:"categoria_id,omitempty"`
	Titulo            string                 `protobuf:"bytes,4,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Descripcion       string                 `protobuf:"bytes,5,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	TipoServicio      TipoServicio           `protobuf:"varint,6,opt,name=tipo_servicio,json=tipoServicio,proto3,enum=publication.TipoServicio" json:"tipo_servicio,omitempty"`
	PrecioBase        int64                  `protobuf:"varint,7,opt,name=precio_base,json=precioBase,proto3" json:"precio_base,omitempty"`
	Ciudad            string                 `protobuf:"bytes,8,opt,name=ciudad,proto3" json:"ciudad,omitempty"`
	Region            string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	Estado            EstadoPublicacion      `protobuf:"varint,10,opt,name=estado,proto3,enum=publication.EstadoPublicacion" json:"estado,omitempty"`
	ImagenesUrls      []string               `protobuf:"bytes,11,rep,name=imagenes_urls,json=imagenesUrls,proto3" json:"imagenes_urls,omitempty"` // RN-25: 1 a 5 imágenes
	Categoria         *Category              `protobuf:"bytes,12,opt,name=categoria,proto3,oneof" json:"categoria,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_publication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{1}
}

func (x *Publication) GetIdPublicacion() uint32 {
	if x != nil {
		return x.IdPublicacion
	}
	return 0
}

func (x *Publication) GetIdUsuarioVendedor() uint32 {
	if x != nil {
		return x.IdUsuarioVendedor
	}
	return 0
}

func (x *Publication) GetCategoriaId() uint32 {
	if x != nil {
		return x.CategoriaId
	}
	return 0
}

func (x *Publication) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Publication) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Publication) GetTipoServicio() TipoServicio {
	if x != nil {
		return x.TipoServicio
	}
	return TipoServicio_TIPO_SERVICIO_UNSPECIFIED
}

func (x *Publication) GetPrecioBase() int64 {
	if x != nil {
		return x.PrecioBase
	}
	return 0
}

func (x *Publication) GetCiudad() string {
	if x != nil {
		return x.Ciudad
	}
	return ""
}

func (x *Publication) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Publication) GetEstado() EstadoPublicacion {
	if x != nil {
		return x.Estado
	}
	return EstadoPublicacion_ESTADO_PUBLICACION_UNSPECIFIED
}

func (x *Publication) GetImagenesUrls() []string {
	if x != nil {
		return x.ImagenesUrls
	}
	return nil
}

func (x *Publication) GetCategoria() *Category {
	if x != nil {
		return x.Categoria
	}
	return nil
}

func (x *Publication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Publication) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaginationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRecords  int64                  `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMeta) Reset() {
	*x = PaginationMeta{}
	mi := &file_publication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMeta) ProtoMessage() {}

func (x *PaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMeta.ProtoReflect.Descriptor instead.
func (*PaginationMeta) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationMeta) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *PaginationMeta) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginationMeta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationMeta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Mensajes para RPC CreatePublication
type CreatePublicationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdUsuarioVendedor uint32                 `protobuf:"varint,1,opt,name=id_usuario_vendedor,json=idUsuarioVendedor,proto3" json:"id_usuario_vendedor,omitempty"`
	CategoriaId       uint32                 `protobuf:"varint,2,opt,name=categoria_id,json=categoriaId,proto3" json:"categoria_id,omitempty"`
	Titulo            string                 `protobuf:"bytes,3,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Descripcion       string                 `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	TipoServicio      TipoServicio           `protobuf:"varint,5,opt,name=tipo_servicio,json=tipoServicio,proto3,enum=publication.TipoServicio" json:"tipo_servicio,omitempty"`
	PrecioBase        int64                  `protobuf:"varint,6,opt,name=precio_base,json=precioBase,proto3" json:"precio_base,omitempty"`
	Ciudad            string                 `protobuf:"bytes,7,opt,name=ciudad,proto3" json:"ciudad,omitempty"`
	Region            string                 `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	ImagenesUrls      []string               `protobuf:"bytes,9,rep,name=imagenes_urls,json=imagenesUrls,proto3" json:"imagenes_urls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePublicationRequest) Reset() {
	*x = CreatePublicationRequest{}
	mi := &file_publication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePublicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicationRequest) ProtoMessage() {}

func (x *CreatePublicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicationRequest.ProtoReflect.Descriptor instead.
func (*CreatePublicationRequest) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePublicationRequest) GetIdUsuarioVendedor() uint32 {
	if x != nil {
		return x.IdUsuarioVendedor
	}
	return 0
}

func (x *CreatePublicationRequest) GetCategoriaId() uint32 {
	if x != nil {
		return x.CategoriaId
	}
	return 0
}

func (x *CreatePublicationRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *CreatePublicationRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CreatePublicationRequest) GetTipoServicio() TipoServicio {
	if x != nil {
		return x.TipoServicio
	}
	return TipoServicio_TIPO_SERVICIO_UNSPECIFIED
}

func (x *CreatePublicationRequest) GetPrecioBase() int64 {
	if x != nil {
		return x.PrecioBase
	}
	return 0
}

func (x *CreatePublicationRequest) GetCiudad() string {
	if x != nil {
		return x.Ciudad
	}
	return ""
}

func (x *CreatePublicationRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreatePublicationRequest) GetImagenesUrls() []string {
	if x != nil {
		return x.ImagenesUrls
	}
	return nil
}

type CreatePublicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publication   *Publication           `protobuf:"bytes,1,opt,name=publication,proto3" json:"publication,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePublicationResponse) Reset() {
	*x = CreatePublicationResponse{}
	mi := &file_publication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePublicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicationResponse) ProtoMessage() {}

func (x *CreatePublicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicationResponse.ProtoReflect.Descriptor instead.
func (*CreatePublicationResponse) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePublicationResponse) GetPublication() *Publication {
	if x != nil {
		return x.Publication
	}
	return nil
}

func (x *CreatePublicationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Mensajes para RPC GetPublication
type GetPublicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPublicacion uint32                 `protobuf:"varint,1,opt,name=id_publicacion,json=idPublicacion,proto3" json:"id_publicacion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicationRequest) Reset() {
	*x = GetPublicationRequest{}
	mi := &file_publication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicationRequest) ProtoMessage() {}

func (x *GetPublicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicationRequest.ProtoReflect.Descriptor instead.
func (*GetPublicationRequest) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{5}
}

func (x *GetPublicationRequest) GetIdPublicacion() uint32 {
	if x != nil {
		return x.IdPublicacion
	}
	return 0
}

type GetPublicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publication   *Publication           `protobuf:"bytes,1,opt,name=publication,proto3" json:"publication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicationResponse) Reset() {
	*x = GetPublicationResponse{}
	mi := &file_publication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicationResponse) ProtoMessage() {}

func (x *GetPublicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicationResponse.ProtoReflect.Descriptor instead.
func (*GetPublicationResponse) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{6}
}

func (x *GetPublicationResponse) GetPublication() *Publication {
	if x != nil {
		return x.Publication
	}
	return nil
}

// Mensajes para RPC ListPublications
type ListPublicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	CategoriaId   *uint32                `protobuf:"varint,3,opt,name=categoria_id,json=categoriaId,proto3,oneof" json:"categoria_id,omitempty"`
	TipoServicio  *TipoServicio          `protobuf:"varint,4,opt,name=tipo_servicio,json=tipoServicio,proto3,enum=publication.TipoServicio,oneof" json:"tipo_servicio,omitempty"`
	ExcludeUserId *uint32                `protobuf:"varint,5,opt,name=exclude_user_id,json=excludeUserId,proto3,oneof" json:"exclude_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicationsRequest) Reset() {
	*x = ListPublicationsRequest{}
	mi := &file_publication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicationsRequest) ProtoMessage() {}

func (x *ListPublicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicationsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicationsRequest) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{7}
}

func (x *ListPublicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPublicationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPublicationsRequest) GetCategoriaId() uint32 {
	if x != nil && x.CategoriaId != nil {
		return *x.CategoriaId
	}
	return 0
}

func (x *ListPublicationsRequest) GetTipoServicio() TipoServicio {
	if x != nil && x.TipoServicio != nil {
		return *x.TipoServicio
	}
	return TipoServicio_TIPO_SERVICIO_UNSPECIFIED
}

func (x *ListPublicationsRequest) GetExcludeUserId() uint32 {
	if x != nil && x.ExcludeUserId != nil {
		return *x.ExcludeUserId
	}
	return 0
}

type ListPublicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publications  []*Publication         `protobuf:"bytes,1,rep,name=publications,proto3" json:"publications,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicationsResponse) Reset() {
	*x = ListPublicationsResponse{}
	mi := &file_publication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicationsResponse) ProtoMessage() {}

func (x *ListPublicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicationsResponse.ProtoReflect.Descriptor instead.
func (*ListPublicationsResponse) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{8}
}

func (x *ListPublicationsResponse) GetPublications() []*Publication {
	if x != nil {
		return x.Publications
	}
	return nil
}

func (x *ListPublicationsResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_publication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{9}
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_publication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_publication_proto_rawDescGZIP(), []int{10}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_publication_proto protoreflect.FileDescriptor

const file_publication_proto_rawDesc = "" +
	"\n" +
	"\x11publication.proto\x12\vpublication\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x89\x01\n" +
	"\bCategory\x12!\n" +
	"\fid_categoria\x18\x01 \x01(\rR\vidCategoria\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\ticono_url\x18\x04 \x01(\tH\x00R\biconoUrl\x88\x01\x01B\f\n" +
	"\n" +
	"_icono_url\"\xed\x04\n" +
	"\vPublication\x12%\n" +
	"\x0eid_publicacion\x18\x01 \x01(\rR\ridPublicacion\x12.\n" +
	"\x13id_usuario_vendedor\x18\x02 \x01(\rR\x11idUsuarioVendedor\x12!\n" +
	"\fcategoria_id\x18\x03 \x01(\rR\vcategoriaId\x12\x16\n" +
	"\x06titulo\x18\x04 \x01(\tR\x06titulo\x12 \n" +
	"\vdescripcion\x18\x05 \x01(\tR\vdescripcion\x12>\n" +
	"\rtipo_servicio\x18\x06 \x01(\x0e2\x19.publication.TipoServicioR\ftipoServicio\x12\x1f\n" +
	"\vprecio_base\x18\a \x01(\x03R\n" +
	"precioBase\x12\x16\n" +
	"\x06ciudad\x18\b \x01(\tR\x06ciudad\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x126\n" +
	"\x06estado\x18\n" +
	" \x01(\x0e2\x1e.publication.EstadoPublicacionR\x06estado\x12#\n" +
	"\rimagenes_urls\x18\v \x03(\tR\fimagenesUrls\x128\n" +
	"\tcategoria\x18\f \x01(\v2\x15.publication.CategoryH\x00R\tcategoria\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_categoria\"\x8f\x01\n" +
	"\x0ePaginationMeta\x12#\n" +
	"\rtotal_records\x18\x01 \x01(\x03R\ftotalRecords\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xdd\x02\n" +
	"\x18CreatePublicationRequest\x12.\n" +
	"\x13id_usuario_vendedor\x18\x01 \x01(\rR\x11idUsuarioVendedor\x12!\n" +
	"\fcategoria_id\x18\x02 \x01(\rR\vcategoriaId\x12\x16\n" +
	"\x06titulo\x18\x03 \x01(\tR\x06titulo\x12 \n" +
	"\vdescripcion\x18\x04 \x01(\tR\vdescripcion\x12>\n" +
	"\rtipo_servicio\x18\x05 \x01(\x0e2\x19.publication.TipoServicioR\ftipoServicio\x12\x1f\n" +
	"\vprecio_base\x18\x06 \x01(\x03R\n" +
	"precioBase\x12\x16\n" +
	"\x06ciudad\x18\a \x01(\tR\x06ciudad\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\x12#\n" +
	"\rimagenes_urls\x18\t \x03(\tR\fimagenesUrls\"q\n" +
	"\x19CreatePublicationResponse\x12:\n" +
	"\vpublication\x18\x01 \x01(\v2\x18.publication.PublicationR\vpublication\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x15GetPublicationRequest\x12%\n" +
	"\x0eid_publicacion\x18\x01 \x01(\rR\ridPublicacion\"T\n" +
	"\x16GetPublicationResponse\x12:\n" +
	"\vpublication\x18\x01 \x01(\v2\x18.publication.PublicationR\vpublication\"\x94\x02\n" +
	"\x17ListPublicationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12&\n" +
	"\fcategoria_id\x18\x03 \x01(\rH\x00R\vcategoriaId\x88\x01\x01\x12C\n" +
	"\rtipo_servicio\x18\x04 \x01(\x0e2\x19.publication.TipoServicioH\x01R\ftipoServicio\x88\x01\x01\x12+\n" +
	"\x0fexclude_user_id\x18\x05 \x01(\rH\x02R\rexcludeUserId\x88\x01\x01B\x0f\n" +
	"\r_categoria_idB\x10\n" +
	"\x0e_tipo_servicioB\x12\n" +
	"\x10_exclude_user_id\"\x89\x01\n" +
	"\x18ListPublicationsResponse\x12<\n" +
	"\fpublications\x18\x01 \x03(\v2\x18.publication.PublicationR\fpublications\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.publication.PaginationMetaR\x04meta\"\x16\n" +
	"\x14GetCategoriesRequest\"N\n" +
	"\x15GetCategoriesResponse\x125\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x15.publication.CategoryR\n" +
	"categories*F\n" +
	"\fTipoServicio\x12\x1d\n" +
	"\x19TIPO_SERVICIO_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OFERTA\x10\x01\x12\v\n" +
	"\aDEMANDA\x10\x02*o\n" +
	"\x11EstadoPublicacion\x12\"\n" +
	"\x1eESTADO_PUBLICACION_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVO\x10\x01\x12\v\n" +
	"\aPAUSADO\x10\x02\x12\x0e\n" +
	"\n" +
	"COMPLETADO\x10\x03\x12\r\n" +
	"\tELIMINADO\x10\x042\x86\x03\n" +
	"\x12PublicationService\x12n\n" +
	"\rGetCategories\x12!.publication.GetCategoriesRequest\x1a\".publication.GetCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12\x84\x01\n" +
	"\x0eGetPublication\x12\".publication.GetPublicationRequest\x1a#.publication.GetPublicationResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/publications/{id_publicacion}\x12y\n" +
	"\x10ListPublications\x12$.publication.ListPublicationsRequest\x1a%.publication.ListPublicationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/publicationsBlZjgithub.com/AlvaroFPM/Allin1_Taller_de_integracion_III/backend-go/internal/api/pb/publication;publicationpbb\x06proto3"

var (
	file_publication_proto_rawDescOnce sync.Once
	file_publication_proto_rawDescData []byte
)

func file_publication_proto_rawDescGZIP() []byte {
	file_publication_proto_rawDescOnce.Do(func() {
		file_publication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publication_proto_rawDesc), len(file_publication_proto_rawDesc)))
	})
	return file_publication_proto_rawDescData
}

var file_publication_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_publication_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_publication_proto_goTypes = []any{
	(TipoServicio)(0),                 // 0: publication.TipoServicio
	(EstadoPublicacion)(0),            // 1: publication.EstadoPublicacion
	(*Category)(nil),                  // 2: publication.Category
	(*Publication)(nil),               // 3: publication.Publication
	(*PaginationMeta)(nil),            // 4: publication.PaginationMeta
	(*CreatePublicationRequest)(nil),  // 5: publication.CreatePublicationRequest
	(*CreatePublicationResponse)(nil), // 6: publication.CreatePublicationResponse
	(*GetPublicationRequest)(nil),     // 7: publication.GetPublicationRequest
	(*GetPublicationResponse)(nil),    // 8: publication.GetPublicationResponse
	(*ListPublicationsRequest)(nil),   // 9: publication.ListPublicationsRequest
	(*ListPublicationsResponse)(nil),  // 10: publication.ListPublicationsResponse
	(*GetCategoriesRequest)(nil),      // 11: publication.GetCategoriesRequest
	(*GetCategoriesResponse)(nil),     // 12: publication.GetCategoriesResponse
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_publication_proto_depIdxs = []int32{
	0,  // 0: publication.Publication.tipo_servicio:type_name -> publication.TipoServicio
	1,  // 1: publication.Publication.estado:type_name -> publication.EstadoPublicacion
	2,  // 2: publication.Publication.categoria:type_name -> publication.Category
	13, // 3: publication.Publication.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: publication.Publication.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: publication.CreatePublicationRequest.tipo_servicio:type_name -> publication.TipoServicio
	3,  // 6: publication.CreatePublicationResponse.publication:type_name -> publication.Publication
	3,  // 7: publication.GetPublicationResponse.publication:type_name -> publication.Publication
	0,  // 8: publication.ListPublicationsRequest.tipo_servicio:type_name -> publication.TipoServicio
	3,  // 9: publication.ListPublicationsResponse.publications:type_name -> publication.Publication
	4,  // 10: publication.ListPublicationsResponse.meta:type_name -> publication.PaginationMeta
	2,  // 11: publication.GetCategoriesResponse.categories:type_name -> publication.Category
	11, // 12: publication.PublicationService.GetCategories:input_type -> publication.GetCategoriesRequest
	7,  // 13: publication.PublicationService.GetPublication:input_type -> publication.GetPublicationRequest
	9,  // 14: publication.PublicationService.ListPublications:input_type -> publication.ListPublicationsRequest
	12, // 15: publication.PublicationService.GetCategories:output_type -> publication.GetCategoriesResponse
	8,  // 16: publication.PublicationService.GetPublication:output_type -> publication.GetPublicationResponse
	10, // 17: publication.PublicationService.ListPublications:output_type -> publication.ListPublicationsResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_publication_proto_init() }
func file_publication_proto_init() {
	if File_publication_proto != nil {
		return
	}
	file_publication_proto_msgTypes[0].OneofWrappers = []any{}
	file_publication_proto_msgTypes[1].OneofWrappers = []any{}
	file_publication_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publication_proto_rawDesc), len(file_publication_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publication_proto_goTypes,
		DependencyIndexes: file_publication_proto_depIdxs,
		EnumInfos:         file_publication_proto_enumTypes,
		MessageInfos:      file_publication_proto_msgTypes,
	}.Build()
	File_publication_proto = out.File
	file_publication_proto_goTypes = nil
	file_publication_proto_depIdxs = nil
}
